package ufes.republica.view.mantertarefa;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import ufes.republica.dao.TarefaDAO;
import ufes.republica.model.Tarefa;
import ufes.republica.model.UsuarioLogin;
import ufes.republica.view.TelaInicial;

public class P0301 extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;

    private UsuarioLogin usuarioLogin;
    
    public P0301(UsuarioLogin usuarioLogin) {
        initComponents();
        this.usuarioLogin = usuarioLogin;
        
        modelo = (DefaultTableModel) jTableTarefa.getModel();
        try {
            String aux = "não";
            TarefaDAO tarefaDAO = new TarefaDAO();
            ArrayList<Tarefa> tarefas = tarefaDAO.getAll();
            for (Tarefa t : tarefas) {
                if(t.isFinalizada()){
                    aux = "sim";
                }
                tarefaDAO = new TarefaDAO();
                modelo.addRow(new Object[]{
                    t.getId(),
                    t.getDescricao(),
                    tarefaDAO.getNomeResponsavel(t),
                    t.getDataAgendamento().toString(),
                    t.getDataTermino().toString(),
                    aux
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(P0301.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefa = new javax.swing.JTable();
        jComboBoxPessoa = new javax.swing.JComboBox<>();
        jButtonCadastrar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tarefa", "Responsáveis", "Data Agendamento", "Data de Término", "Realizada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTarefa.setRowHeight(25);
        jScrollPane1.setViewportView(jTableTarefa);
        if (jTableTarefa.getColumnModel().getColumnCount() > 0) {
            jTableTarefa.getColumnModel().getColumn(0).setResizable(false);
            jTableTarefa.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableTarefa.getColumnModel().getColumn(1).setResizable(false);
            jTableTarefa.getColumnModel().getColumn(2).setResizable(false);
            jTableTarefa.getColumnModel().getColumn(3).setResizable(false);
            jTableTarefa.getColumnModel().getColumn(4).setResizable(false);
            jTableTarefa.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 53, 1250, 410));

        jComboBoxPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa", "Descrição" }));
        jComboBoxPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPessoaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 123, -1));

        jButtonCadastrar.setText("Cadastrar Nova Tarefa");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 170, -1));

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 10, 495, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 88, -1));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 480, 88, -1));

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 480, 88, -1));

        setBounds(0, 0, 1292, 574);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        P0302 cad = new P0302(usuarioLogin);
        TelaInicial.Desktop.add(cad);
        cad.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        P0302 cad = new P0302(this.usuarioLogin);
        TelaInicial.Desktop.add(cad);
        cad.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jComboBoxPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPessoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JComboBox<String> jComboBoxPessoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTarefa;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables

    public UsuarioLogin getUsuarioLogin() {
        return usuarioLogin;
    }

    public void setUsuarioLogin(UsuarioLogin usuarioLogin) {
        this.usuarioLogin = usuarioLogin;
    }
}
